### ISSUE TITLE
Library doesn't work with docker desktop v4.7.0

### ISSUE THREAD

**Issue by danioo** [SwissLife-OSS/squadron#114]
When updated docker desktop to v4.7.0 he library stopped working and throws exceptions:
`
Squadron.ContainerException : Error in ImageExists: mongo:latest
---- Docker.DotNet.DockerApiException : Docker API responded with status code=BadRequest, response=400 Bad Request
`

1. Update docker desktop to v4.7.0
2. Run tests using squadrom's mongo instance

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1 (19043.1466)

**Comment by RohrerF** [comment]
I experienced the same issue
after updating Docker.DotNet to the latest Version, the tests in this repository work again on my machine.
Created PR #115

**Comment by Carael** [comment]
Fixed in newest preview release 0.15.0-preview.3. Closing this issue.
