### ISSUE TITLE
How to run a Container with custom Parameters

### ISSUE THREAD

**Issue by tsinghammer** [SwissLife-OSS/squadron#129]
I'm trying to add support for OPA to Squadron.
My plan was to use the REST API OPA offers.
The problem I think I have is that the container immediately exists after it started. When `IsReadyAsync `of my status object is called, the container has already exited and the connection to the health endpoint results in _Target machine actively refused_.

On the command line I would run the container like so: `docker run -it --rm -p 8181:8181 openpolicyagent/opa run --addr :8181`

Can I pass the same arguments before calling `base.InitializeAsync()` somehow so that the initialization runs the container with these parameters?

**Comment by glucaci** [comment]
If you use `GenericContainerResource` (e.g. [here](https://github.com/SwissLife-OSS/squadron/blob/master/src/Core.Tests/GenericContainerWithMultiplePortsTests.cs)) or any other resource, you can create custom `ResourceOptions` and in the `Configure` you can use the `AddCmd` method of the `ContainerResourceBuilder`.
This will be used as [start parameter](https://github.com/SwissLife-OSS/squadron/blob/11f298faef1f0443a86c33b83fe4d2aa8193125d/src/Core/DockerContainerManager.cs#L340) for container.

**Comment by glucaci** [comment]
I will close this if it solved your question. Please feel free to open another one
