### ISSUE TITLE
Prefere Local Image Default

### ISSUE THREAD

**Issue by PascalSenn** [SwissLife-OSS/squadron#77]
With the new restrictions of docker you can quickly run into the issue that you pull to many images from the server.

It is possible to configure to prefere the local image in `ContainerResourceSettings`.
At the moment it is set to false

```csharp
        public bool PreferLocalImage {get; internal set;} = false;
```

I think we should change this to true

**Comment by philbir** [comment]
Yes, totally makes sense to change this to `true`.

**Comment by PascalSenn** [comment]
added a PR
