### ISSUE TITLE
Volume bindings are not working due to wrong usage of docker cli

### ISSUE THREAD

**Issue by fredericbirke** [SwissLife-OSS/squadron#89]
There is one testcase found [here](https://github.com/SwissLife-OSS/squadron/blob/master/src/Core.Tests/GenericContainerWithVolumneTests.cs), which passes, but doesn't actually validate if the volume works. If you start the testcase and inspect the container, you will see, that the `.AddVolume("/dev/shm:/dev/shm");` call of the builder will actually result in a volume, that maps from the docker directory onto the path `"/dev/shm:/dev/shm"` in the container.
See:
![grafik](https://user-images.githubusercontent.com/9481836/109300930-7ec05380-7837-11eb-9535-5384b4405490.png)
and
https://docs.docker.com/engine/api/v1.41/#operation/ContainerCreate

I'll try to fix this issue and provide a PR for fixing it.

**Comment by RohrerF** [comment]
fixed in #107
